### ISSUE TITLE
Tag / value enumeration values for Reference Category a "-" should be converted to "_"

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-java-jackson-store#16]
Example - reference category PACKAGE-MANAGER should be converted to the enum PACKAGE_MANAGER when deserializing and converted back to the dash when serializing.

**Comment by MarkusTe** [comment]
Maybe you can join forces on this?
[https://github.com/spdx/spdx-spec/issues/473](https://github.com/spdx/spdx-spec/issues/473)

**Comment by goneall** [comment]
In reviewing the spec, only Reference Category uses dashes.

**Comment by goneall** [comment]
Based on  https://github.com/spdx/spdx-spec/issues/473 comments, closing this issue as the decision in the SPDX Spec issue is to leave the serialization as is.

**Comment by goneall** [comment]
Note that I made changes in a branch named issue16 if we change our minds and would like to convert underscrores to dashes in the serialization.
