### ISSUE TITLE
Sorting of properties

### ISSUE THREAD

**Issue by MarkusTe** [spdx/spdx-java-jackson-store#17]
As mentioned [here](https://github.com/spdx/spdx-online-tools/issues/307), it would be really helpful and a time-saver to sort the properties always the same way, so random sorting won't pop up in any source diff. WDYT?
PropertyComparator.java is used for sorting.
We are mostly interested in YAML but would propose to sort also in JSON and XML.

**Comment by goneall** [comment]
From looking at the code, it looks like the properties should always be sorted.

Any object properties not listed in the arrays will get sorted alphabetically in this line:
https://github.com/spdx/spdx-java-jackson-store/blob/d9673e80c7566335b242213ceba553b40747a943/src/main/java/org/spdx/jacksonstore/PropertyComparator.java#L85

I did notice that the arrays are not sorted and the packages and files may be in a different order.

I'm going to close this for now.

@MarkusTe if you disagree with the above analysis, please let me know where I went wrong or provide an example and I'll re-open.

Also, if you feel it would help to sort the arrays, please open another issue and I'll take a look at it on the next release.
