### ISSUE TITLE
Translating from TagValue to XML giving weird error

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-java-jackson-store#23]
An example (in tag/value), validated, however when I tried to convert it to XML,  it gave the message: 
Analysis exception processing SPDX file: Document
Describes is not an array - invalid JSON format.

I've mailed the .spdx file in question to @goneall, and will share with anyone else interested.

**Comment by goneall** [comment]
After doing a bit of research, this seems to be a structural problem with XML.  The XML format itself does not retain any list or array information for single elements.

To resolve this, we need to use the schema to determine if any property is a list then manually convert to a JSONArray if there is only a single element.

This is a bit of redesign and may take a while to resolve.

**Comment by goneall** [comment]
This wasn't as bad as I thought - the Jackson code already handles converting list elements to JSONArrays for everything except the document describes.

I creaesd PR #24 to resolve.

**Comment by goneall** [comment]
Resolved with PR #24
