### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by zkr-bp** [spdx/spdx-java-jackson-store#27]
Hello,

The project is missing a LICENSE/LICENSE.md file, which could easly be done [via the github UI.](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

Is this something that can be done, and if not, what are the reasons?

Best Regards,
zkr

**Comment by goneall** [comment]
Resolved with PR #28 

@zkr-bp Thanks for pointing this out.

**Comment by goneall** [comment]
I just checked all the other repos I maintain in SPDX and they all have LICENSE files.  Not sure how I missed this one, but I appreciate @zkr-bp pointing this out.
