### ISSUE TITLE
Error importing JSON files with String objects

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-java-jackson-store#30]
Importing the attached JSON file generates the following error:

`Analysis exception processing SPDX file: string is not a valid SPDX class`
[test.zip](https://github.com/spdx/spdx-java-jackson-store/files/8218387/test.zip)

**Comment by goneall** [comment]
This error is coming from:

https://github.com/spdx/spdx-java-jackson-store/blob/4af94b147228ae75db1d689af919dbc5737cdb36/src/main/java/org/spdx/jacksonstore/JacksonDeSerializer.java#L446

where the object type is OBJECT and it is of type String.

Not sure why JSON deserializer isn't declaring the JSON node type as string, but this can probably be resolved by checking for type `string` and handling appropriately.

**Comment by makdataproj** [comment]
@goneall Hi, I was curious if there are any updates at all?

**Comment by goneall** [comment]
@makdataproj No updates as yet - I'm traveling for the next couple of weeks with limited internet connectivity, but I'll put this on my list of things to make progress on once I'm back online.

**Comment by goneall** [comment]
@makdataproj My initial assessment was incorrect.  The validation errors are due to the input file having a structured object for the creator while the validation is expecting a string with the tag/value format for creator.

I'll add a comment to the original issue and close this one.

**Comment by volviq** [comment]
@goneall  still no comment made in the original ticket. can you make an update?
