### ISSUE TITLE
primaryPackagePurpose uses OPERATING-SYSTEM instead of OPERATING_SYSTEM

### ISSUE THREAD

**Issue by flemminglau** [spdx/spdx-java-jackson-store#69]
It is true that the documentation in SPDX states that the value is OPERATING-SYSTEM but the spec states OPERATING_SYSTEM as being the allowed enumeration.

We have tools that complain about the generated value of OPERATING-SYSTEM.

Should it be fixed in this tool or should we push our counterparts to be more lenient?

**Comment by goneall** [comment]
@flemminglau - I just release version 0.1.5 of the cdx2spdx project which resolves this issue.

Thanks for reporting it.
