### ISSUE TITLE
Issue with online tools - conversion from TV to XML

### ISSUE THREAD

**Issue by rjb4standards** [spdx/spdx-java-jackson-store#7]
I have a spdx TV file that validates fine using the online tools validation tool, however I received an error trying to convert to XML using the online conversion tool: Analysis Exception process SPDX file: Missing SPDX ID

I'm guessing the exception is something else because all of the items seem to have a valid SPDX ID. 

The file I'm trying to convert from TV to XML is available here: https://github.com/rjb4standards/REA-Products/blob/master/SAG-PM.spdx

**Comment by goneall** [comment]
Thanks @rjb4standards for pointing out this error.  I think I have pull requests to address several issues this has uncovered.

The main issue is not catching an invalid SPDX ID in the tag/value file.  If you remove the `@`, it should convert OK.

I'm planning on updating the tools to a new version over the weekend.  The update should catch these error earlier in the process.

**Comment by rjb4standards** [comment]
Gary, 

 

I replaced the @ in SPDXID, but now I see an error when converting to JSON, of a similar issue with License info – as invalid in that same TV file.

 

Thanks,

 

Dick Brooks



 <https://reliableenergyanalytics.com/products> Never trust software, always verify and report! ™

 <http://www.reliableenergyanalytics.com/> http://www.reliableenergyanalytics.com

Email:  <mailto:dick@reliableenergyanalytics.com> dick@reliableenergyanalytics.com

Tel: +1 978-696-1788

**Comment by goneall** [comment]
> I replaced the @ in SPDXID, but now I see an error when converting to JSON, of a similar issue with License info – as invalid in that same TV file.

This may be a known issue: https://github.com/spdx/spdx-online-tools/issues/281

Let me know if the error message is similar to: 
`Invalid license id '__anon__2'. Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.`

If so, it will be fixed in the next update.

If the error is different, please attach the updated tag/value file and I'll take a look at it.

**Comment by goneall** [comment]
Resolved with PR #2
