### ISSUE TITLE
Allow usage of non-default copyManager in JacksonDeSerializer

### ISSUE THREAD

**Issue by martin-bpw** [spdx/spdx-java-jackson-store#75]
This issue/suggestion is closely related to https://github.com/spdx/Spdx-Java-Library/issues/257 . Basically if we use MultiFormatStore, we cannot specify custom copyManager, which lead to case when default copyManager was used. Instead, it would be better to be able to use garbage-collectible copyManager instance instead.

We came across this issue as it led to OOM error on our system:

<img width="661" alt="image" src="https://github.com/user-attachments/assets/63734c94-4fce-4d90-8a24-74971257af97">

**Comment by goneall** [comment]
The `MultiFormatStore` should be picking up the `copyManager` from the SPDX model objects being "copied", not from any parameter or property stored in the `MultiFormatStore`.  If you're creating the objects directly, you can just pass in a different `copyManager`.  From the other issue, it looks like you're using the `LicenseInfoFactory` which doesn't give you an option of passing in null.

I think I have a work around - I'll post it as a comment in the library issue.

**Comment by goneall** [comment]
BTW - That's a lot of IDs in the copy manager - is it possible there is another issue?  Perhaps in the copy manager or SPDX java library?

**Comment by goneall** [comment]
@martin-bpw - Seeing the pull request - I now understand where the use of the copy manager is used.

I'll put a little more thought and review into the PR.

**Comment by martin-bpw** [comment]
@goneall I have two questions:
1. can we close this issue now (is still open, from my pov we can) ?
2. what to do / how can I help to do a release with this issue? That way we can directly use that version instead of maintaining private fork of this with fix (I would prefer to just use official version from maven central ofc)?

**Comment by goneall** [comment]
> @goneall I have two questions:
> 
> 1. can we close this issue now (is still open, from my pov we can) ?

Yes - I'll go ahead and close

> 2. what to do / how can I help to do a release with this issue? That way we can directly use that version instead of maintaining private fork of this with fix (I would prefer to just use official version from maven central ofc)?

I'm planning on releasing an update to all the SPDX Java libraries (including this one) once we finalize the 3.0.1 release of the spec - which should be within a week.  @martin-bpw let me know if that's soon enough.

**Comment by goneall** [comment]
Closing per above comment

**Comment by martin-bpw** [comment]
Yes that sounds soon enough,  thank you.

**Comment by goneall** [comment]
@martin-bpw - Just release [version 2.0.0-RC1](https://github.com/spdx/spdx-java-jackson-store/releases/tag/v2.0.0-RC1) which includes your fix for this issue.

**Comment by martin-bpw** [comment]
@goneall Thank you, I am releasing tomorrow so will let you know if all good soon:).
